//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DaControl.rc
//
#define	IDB_AGENT	101
#define	IDI_DOUBLEAGENT	102
#define	IDR_DACONTROLMOD	103
#define	IDR_DACONTROL	104
#define	IDR_DACTLANIMATIONNAMES	105
#define	IDR_DACTLAUDIOOUTPUT	106
#define	IDR_DACTLBALLOON	107
#define	IDR_DACTLCHARACTER	108
#define	IDR_DACTLCHARACTERFILES	109
#define	IDR_DACTLCHARACTERS	110
#define	IDR_DACTLCOMMAND	111
#define	IDR_DACTLCOMMANDS	112
#define	IDR_DACTLCOMMANDSWINDOW	113
#define	IDR_DACTLPROPERTYSHEET	114
#define	IDR_DACTLRECOGNITIONENGINE	115
#define	IDR_DACTLRECOGNITIONENGINES	116
#define	IDR_DACTLREQUEST	117
#define	IDR_DACTLSPEECHENGINE	118
#define	IDR_DACTLSPEECHENGINES	119
#define	IDR_DACTLSPEECHINPUT	120
#define	IDR_DACTLUSERINPUT	121
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
