#pragma once

template <class T>
class CProxy_DaCtlEvents : public IConnectionPointImpl<T, &__uuidof(_DaCtlEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};

template <class T>
class CProxy_AgentEvents : public IConnectionPointImpl<T, &__uuidof(_AgentEvents), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
