//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DaServer.rc
//
#define	IDR_DAEMULATION	3
#define	IDR_DASERVER	4
#define	IDR_DASERVERAPP	5
#define	IDR_DASVRANIMATIONNAMES	6
#define	IDR_DASVRAUDIOOUTPUT	7
#define	IDR_DASVRBALLOON	8
#define	IDR_DASVRCHARACTER	9
#define	IDR_DASVRCHARACTERFILES	10
#define	IDR_DASVRCOMMAND	11
#define	IDR_DASVRCOMMANDS	12
#define	IDR_DASVRCOMMANDSWINDOW	13
#define	IDR_DASVRFORMATTEDTEXT	14
#define	IDR_DASVRPROPERTYSHEET	15
#define	IDR_DASVRSETTINGS	16
#define	IDR_DASVRSPEECHINPUT	17
#define	IDR_DASVRSRENGINE	18
#define	IDR_DASVRSRENGINES	19
#define	IDR_DASVRTTSENGINE	20
#define	IDR_DASVRTTSENGINES	21
#define	IDR_DASVRUSERINPUT	22
#define	IDR_DASVRTTSPRIVATE	23
#define	IDR_FIXED_CPL_ELEVATED_DESC	2
#define	IDR_FIXED_DASERVER	1
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
