//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentCharacterEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentCharacterEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthClosed {
            get {
                object obj = ResourceManager.GetObject("BmpMouthClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthMedium {
            get {
                object obj = ResourceManager.GetObject("BmpMouthMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthNarrow {
            get {
                object obj = ResourceManager.GetObject("BmpMouthNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide1 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide2 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide3 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide4 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon IconDoubleAgent {
            get {
                object obj = ResourceManager.GetObject("IconDoubleAgent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditCopy {
            get {
                object obj = ResourceManager.GetObject("ImgEditCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditCut {
            get {
                object obj = ResourceManager.GetObject("ImgEditCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditDelete {
            get {
                object obj = ResourceManager.GetObject("ImgEditDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditPaste {
            get {
                object obj = ResourceManager.GetObject("ImgEditPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditRedo {
            get {
                object obj = ResourceManager.GetObject("ImgEditRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditUndo {
            get {
                object obj = ResourceManager.GetObject("ImgEditUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFileNew {
            get {
                object obj = ResourceManager.GetObject("ImgFileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFileOpen {
            get {
                object obj = ResourceManager.GetObject("ImgFileOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFilePrint {
            get {
                object obj = ResourceManager.GetObject("ImgFilePrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFilePrintPreview {
            get {
                object obj = ResourceManager.GetObject("ImgFilePrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFileSave {
            get {
                object obj = ResourceManager.GetObject("ImgFileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgHelpAbout {
            get {
                object obj = ResourceManager.GetObject("ImgHelpAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgLock {
            get {
                object obj = ResourceManager.GetObject("ImgLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMouthClosed {
            get {
                object obj = ResourceManager.GetObject("ImgMouthClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMouthMedium {
            get {
                object obj = ResourceManager.GetObject("ImgMouthMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMouthNarrow {
            get {
                object obj = ResourceManager.GetObject("ImgMouthNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMouthWide1 {
            get {
                object obj = ResourceManager.GetObject("ImgMouthWide1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMouthWide2 {
            get {
                object obj = ResourceManager.GetObject("ImgMouthWide2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMouthWide3 {
            get {
                object obj = ResourceManager.GetObject("ImgMouthWide3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMouthWide4 {
            get {
                object obj = ResourceManager.GetObject("ImgMouthWide4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveDown {
            get {
                object obj = ResourceManager.GetObject("ImgMoveDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveLeft {
            get {
                object obj = ResourceManager.GetObject("ImgMoveLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveRight {
            get {
                object obj = ResourceManager.GetObject("ImgMoveRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveUp {
            get {
                object obj = ResourceManager.GetObject("ImgMoveUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMute {
            get {
                object obj = ResourceManager.GetObject("ImgMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNavigateBack {
            get {
                object obj = ResourceManager.GetObject("ImgNavigateBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNavigateForward {
            get {
                object obj = ResourceManager.GetObject("ImgNavigateForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPause {
            get {
                object obj = ResourceManager.GetObject("ImgPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPlay {
            get {
                object obj = ResourceManager.GetObject("ImgPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgRepeat {
            get {
                object obj = ResourceManager.GetObject("ImgRepeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgRun {
            get {
                object obj = ResourceManager.GetObject("ImgRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftDown {
            get {
                object obj = ResourceManager.GetObject("ImgShiftDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftLeft {
            get {
                object obj = ResourceManager.GetObject("ImgShiftLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftRight {
            get {
                object obj = ResourceManager.GetObject("ImgShiftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftUp {
            get {
                object obj = ResourceManager.GetObject("ImgShiftUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShowBranching {
            get {
                object obj = ResourceManager.GetObject("ImgShowBranching", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShowExitBranching {
            get {
                object obj = ResourceManager.GetObject("ImgShowExitBranching", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSkipBack {
            get {
                object obj = ResourceManager.GetObject("ImgSkipBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSkipForward {
            get {
                object obj = ResourceManager.GetObject("ImgSkipForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgStop {
            get {
                object obj = ResourceManager.GetObject("ImgStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSwap {
            get {
                object obj = ResourceManager.GetObject("ImgSwap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewLarge {
            get {
                object obj = ResourceManager.GetObject("ImgViewLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewMedium {
            get {
                object obj = ResourceManager.GetObject("ImgViewMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewSmall {
            get {
                object obj = ResourceManager.GetObject("ImgViewSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang4105\deflangfe4105{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}}
        ///{\colortbl ;\red53\green56\blue42;\red0\green0\blue255;\red255\green255\blue255;}
        ///{\stylesheet{ Normal;}{\s1 heading 1;}{\s2 heading 2;}{\s3 heading 3;}{\s4 heading 4;}}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\cbpat3\nowidctlpar\s3\sa200\sl240\slmult1\qc\cf1\b\f0\fs22 GNU GENERAL PUBLIC LICENSE\par
        ///\pard\cbpat3\nowidctlpar\sa200\sl240\slmult1\qc\b0\fs18 Version 3, 29 June 2007\par
        ///\pard [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseDetails {
            get {
                return ResourceManager.GetString("LicenseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang4105{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\f0\fs18 Double Agent is free software, distributed in the hope that it will be useful, but with ABSOLUTELY NO WARRANTY.\par
        ///\par
        ///You can redistribute it and/or modify it under the terms of the \b GNU General Public License\b0  as published by the Free Software Foundation.  Click below to read a copy of the license.\par
        ///\par
        ///Double Agent is available for download at h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseIntro {
            get {
                return ResourceManager.GetString("LicenseIntro", resourceCulture);
            }
        }
    }
}
