//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DaControl.rc
//
#define	FIXED_IDB_AGENT	101
#define	FIXED_IDI_DOUBLEAGENT	102
#define	IDR_DACONTROL	6000
#define	IDR_DACONTROLMOD	6001
#define	IDR_DACTLANIMATIONNAMES	6002
#define	IDR_DACTLAUDIOOUTPUT	6003
#define	IDR_DACTLBALLOON	6004
#define	IDR_DACTLCHARACTER	6005
#define	IDR_DACTLCHARACTERFILES	6006
#define	IDR_DACTLCHARACTERS	6007
#define	IDR_DACTLCOMMAND	6008
#define	IDR_DACTLCOMMANDS	6009
#define	IDR_DACTLCOMMANDSWINDOW	6010
#define	IDR_DACTLFORMATTEDTEXT	6011
#define	IDR_DACTLPROPERTYSHEET	6012
#define	IDR_DACTLREQUEST	6013
#define	IDR_DACTLSETTINGS	6014
#define	IDR_DACTLSPEECHINPUT	6015
#define	IDR_DACTLSRENGINE	6016
#define	IDR_DACTLSRENGINES	6017
#define	IDR_DACTLTTSENGINE	6018
#define	IDR_DACTLTTSENGINES	6019
#define	IDR_DACTLUSERINPUT	6020
#define	IDR_DACTLTTSPRIVATE	6021
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           125
#endif
#endif
