//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DaServer.rc
//
#define	IDR_FIXED_DASERVER	1
#define	IDR_DAEMULATION	2
#define	IDR_DASERVER	3
#define	IDR_DASERVERAPP	4
#define	IDR_DASVRANIMATIONNAMES	5
#define	IDR_DASVRAUDIOOUTPUT	6
#define	IDR_DASVRBALLOON	7
#define	IDR_DASVRCHARACTER	8
#define	IDR_DASVRCHARACTERFILES	9
#define	IDR_DASVRCOMMAND	10
#define	IDR_DASVRCOMMANDS	11
#define	IDR_DASVRCOMMANDSWINDOW	12
#define	IDR_DASVRPROPERTYSHEET	13
#define	IDR_DASVRSRENGINE	14
#define	IDR_DASVRSRENGINES	15
#define	IDR_DASVRTTSENGINE	16
#define	IDR_DASVRTTSENGINES	17
#define	IDR_DASVRSPEECHINPUT	18
#define	IDR_DASVRUSERINPUT	19
#define	IDR_DASVRSETTINGS	21
#define	IDS_CPL_ELEVATED_DESC	20
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
