//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentCharacterEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentCharacterEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon DoubleAgent {
            get {
                object obj = ResourceManager.GetObject("DoubleAgent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string EditCopy {
            get {
                return ResourceManager.GetString("EditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy selected text.
        /// </summary>
        internal static string EditCopyText {
            get {
                return ResourceManager.GetString("EditCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy {0}.
        /// </summary>
        internal static string EditCopyThis {
            get {
                return ResourceManager.GetString("EditCopyThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string EditCut {
            get {
                return ResourceManager.GetString("EditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cut selected text.
        /// </summary>
        internal static string EditCutText {
            get {
                return ResourceManager.GetString("EditCutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t {0}.
        /// </summary>
        internal static string EditCutThis {
            get {
                return ResourceManager.GetString("EditCutThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string EditDelete {
            get {
                return ResourceManager.GetString("EditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete selected text.
        /// </summary>
        internal static string EditDeleteText {
            get {
                return ResourceManager.GetString("EditDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete {0}.
        /// </summary>
        internal static string EditDeleteThis {
            get {
                return ResourceManager.GetString("EditDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string EditPaste {
            get {
                return ResourceManager.GetString("EditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste text.
        /// </summary>
        internal static string EditPasteText {
            get {
                return ResourceManager.GetString("EditPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste {0}.
        /// </summary>
        internal static string EditPasteThis {
            get {
                return ResourceManager.GetString("EditPasteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string EditRedo {
            get {
                return ResourceManager.GetString("EditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo {0}.
        /// </summary>
        internal static string EditRedoThis {
            get {
                return ResourceManager.GetString("EditRedoThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string EditUndo {
            get {
                return ResourceManager.GetString("EditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo typing.
        /// </summary>
        internal static string EditUndoText {
            get {
                return ResourceManager.GetString("EditUndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo {0}.
        /// </summary>
        internal static string EditUndoThis {
            get {
                return ResourceManager.GetString("EditUndoThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth.
        /// </summary>
        internal static string MouthOverlay {
            get {
                return ResourceManager.GetString("MouthOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-closed.
        /// </summary>
        internal static string MouthOverlayClosed {
            get {
                return ResourceManager.GetString("MouthOverlayClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-medium.
        /// </summary>
        internal static string MouthOverlayMedium {
            get {
                return ResourceManager.GetString("MouthOverlayMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-narrow.
        /// </summary>
        internal static string MouthOverlayNarrow {
            get {
                return ResourceManager.GetString("MouthOverlayNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-1.
        /// </summary>
        internal static string MouthOverlayWide1 {
            get {
                return ResourceManager.GetString("MouthOverlayWide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-2.
        /// </summary>
        internal static string MouthOverlayWide2 {
            get {
                return ResourceManager.GetString("MouthOverlayWide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-3.
        /// </summary>
        internal static string MouthOverlayWide3 {
            get {
                return ResourceManager.GetString("MouthOverlayWide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-4.
        /// </summary>
        internal static string MouthOverlayWide4 {
            get {
                return ResourceManager.GetString("MouthOverlayWide4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation &quot;{0}&quot; already exists..
        /// </summary>
        internal static string MsgDuplicateAnimation {
            get {
                return ResourceManager.GetString("MsgDuplicateAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as {0} failed..
        /// </summary>
        internal static string MsgFailedSaveAs {
            get {
                return ResourceManager.GetString("MsgFailedSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid character file..
        /// </summary>
        internal static string MsgInvalidFile {
            get {
                return ResourceManager.GetString("MsgInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use &quot;Save As&quot; with the same file name..
        /// </summary>
        internal static string MsgInvalidSaveAs {
            get {
                return ResourceManager.GetString("MsgInvalidSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contain a valid palette..
        /// </summary>
        internal static string MsgNoFilePalette {
            get {
                return ResourceManager.GetString("MsgNoFilePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to {0}?.
        /// </summary>
        internal static string MsgSaveFile {
            get {
                return ResourceManager.GetString("MsgSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation {0}.
        /// </summary>
        internal static string TitleAnimation {
            get {
                return ResourceManager.GetString("TitleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Balloon.
        /// </summary>
        internal static string TitleBalloon {
            get {
                return ResourceManager.GetString("TitleBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name {1}.
        /// </summary>
        internal static string TitleCharacterName {
            get {
                return ResourceManager.GetString("TitleCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame {0}.
        /// </summary>
        internal static string TitleFrame {
            get {
                return ResourceManager.GetString("TitleFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - {0}.
        /// </summary>
        internal static string TitleFrameAnimation {
            get {
                return ResourceManager.GetString("TitleFrameAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0}.
        /// </summary>
        internal static string TitleImage {
            get {
                return ResourceManager.GetString("TitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - {0}.
        /// </summary>
        internal static string TitleImageFrame {
            get {
                return ResourceManager.GetString("TitleImageFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} overlay.
        /// </summary>
        internal static string TitleOverlay {
            get {
                return ResourceManager.GetString("TitleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - {0}.
        /// </summary>
        internal static string TitleOverlayFrame {
            get {
                return ResourceManager.GetString("TitleOverlayFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state {0}.
        /// </summary>
        internal static string TitleState {
            get {
                return ResourceManager.GetString("TitleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-to-Speech.
        /// </summary>
        internal static string TitleTts {
            get {
                return ResourceManager.GetString("TitleTts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change {0}.
        /// </summary>
        internal static string UndoAnimationName {
            get {
                return ResourceManager.GetString("UndoAnimationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string UndoAnimationNames {
            get {
                return ResourceManager.GetString("UndoAnimationNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string UndoAnimationSize {
            get {
                return ResourceManager.GetString("UndoAnimationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame order.
        /// </summary>
        internal static string UndoFrameOrder {
            get {
                return ResourceManager.GetString("UndoFrameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new frame duration.
        /// </summary>
        internal static string UndoNewFrameDuration {
            get {
                return ResourceManager.GetString("UndoNewFrameDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palette.
        /// </summary>
        internal static string UndoPalette {
            get {
                return ResourceManager.GetString("UndoPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return animation.
        /// </summary>
        internal static string UndoReturnAnimation {
            get {
                return ResourceManager.GetString("UndoReturnAnimation", resourceCulture);
            }
        }
    }
}
