//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentCharacterEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgentCharacterEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthClosed {
            get {
                object obj = ResourceManager.GetObject("BmpMouthClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthMedium {
            get {
                object obj = ResourceManager.GetObject("BmpMouthMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthNarrow {
            get {
                object obj = ResourceManager.GetObject("BmpMouthNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide1 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide2 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide3 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BmpMouthWide4 {
            get {
                object obj = ResourceManager.GetObject("BmpMouthWide4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string EditAdd {
            get {
                return ResourceManager.GetString("EditAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new animation.
        /// </summary>
        internal static string EditAddAnimation {
            get {
                return ResourceManager.GetString("EditAddAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add an animation a new animation name is required.
        /// </summary>
        internal static string EditAddAnimation0 {
            get {
                return ResourceManager.GetString("EditAddAnimation0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add animation &quot;{0}&quot;.
        /// </summary>
        internal static string EditAddAnimation1 {
            get {
                return ResourceManager.GetString("EditAddAnimation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string EditAddThis {
            get {
                return ResourceManager.GetString("EditAddThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image file.
        /// </summary>
        internal static string EditChooseFile {
            get {
                return ResourceManager.GetString("EditChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose {0} image file.
        /// </summary>
        internal static string EditChooseThisFile {
            get {
                return ResourceManager.GetString("EditChooseThisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string EditCopy {
            get {
                return ResourceManager.GetString("EditCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy selected text.
        /// </summary>
        internal static string EditCopyText {
            get {
                return ResourceManager.GetString("EditCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy {0}.
        /// </summary>
        internal static string EditCopyThis {
            get {
                return ResourceManager.GetString("EditCopyThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t.
        /// </summary>
        internal static string EditCut {
            get {
                return ResourceManager.GetString("EditCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cut selected text.
        /// </summary>
        internal static string EditCutText {
            get {
                return ResourceManager.GetString("EditCutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cu&amp;t {0}.
        /// </summary>
        internal static string EditCutThis {
            get {
                return ResourceManager.GetString("EditCutThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string EditDelete {
            get {
                return ResourceManager.GetString("EditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete selected text.
        /// </summary>
        internal static string EditDeleteText {
            get {
                return ResourceManager.GetString("EditDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete {0}.
        /// </summary>
        internal static string EditDeleteThis {
            get {
                return ResourceManager.GetString("EditDeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make {0} later.
        /// </summary>
        internal static string EditMoveFrameDown {
            get {
                return ResourceManager.GetString("EditMoveFrameDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make {0} earlier.
        /// </summary>
        internal static string EditMoveFrameUp {
            get {
                return ResourceManager.GetString("EditMoveFrameUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring {0} forward.
        /// </summary>
        internal static string EditMoveImageDown {
            get {
                return ResourceManager.GetString("EditMoveImageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send {0} back.
        /// </summary>
        internal static string EditMoveImageUp {
            get {
                return ResourceManager.GetString("EditMoveImageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string EditPaste {
            get {
                return ResourceManager.GetString("EditPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (add) {0}.
        /// </summary>
        internal static string EditPasteAdd {
            get {
                return ResourceManager.GetString("EditPasteAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To paste (add) an animation a new animation name is required.
        /// </summary>
        internal static string EditPasteAnimation0 {
            get {
                return ResourceManager.GetString("EditPasteAnimation0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (add) {1} from {0}.
        /// </summary>
        internal static string EditPasteAs {
            get {
                return ResourceManager.GetString("EditPasteAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the copied frame.
        /// </summary>
        internal static string EditPasteFrameSource {
            get {
                return ResourceManager.GetString("EditPasteFrameSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the copied image.
        /// </summary>
        internal static string EditPasteImageSource {
            get {
                return ResourceManager.GetString("EditPasteImageSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (replace) {1} with {0}.
        /// </summary>
        internal static string EditPasteOver {
            get {
                return ResourceManager.GetString("EditPasteOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (replace) {0}.
        /// </summary>
        internal static string EditPasteReplace {
            get {
                return ResourceManager.GetString("EditPasteReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste text.
        /// </summary>
        internal static string EditPasteText {
            get {
                return ResourceManager.GetString("EditPasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste {0}.
        /// </summary>
        internal static string EditPasteThis {
            get {
                return ResourceManager.GetString("EditPasteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string EditRedo {
            get {
                return ResourceManager.GetString("EditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo {0}.
        /// </summary>
        internal static string EditRedoThis {
            get {
                return ResourceManager.GetString("EditRedoThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string EditUndo {
            get {
                return ResourceManager.GetString("EditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo typing.
        /// </summary>
        internal static string EditUndoText {
            get {
                return ResourceManager.GetString("EditUndoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo {0}.
        /// </summary>
        internal static string EditUndoThis {
            get {
                return ResourceManager.GetString("EditUndoThis", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon IconDoubleAgent {
            get {
                object obj = ResourceManager.GetObject("IconDoubleAgent", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditCopy {
            get {
                object obj = ResourceManager.GetObject("ImgEditCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditCut {
            get {
                object obj = ResourceManager.GetObject("ImgEditCut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditDelete {
            get {
                object obj = ResourceManager.GetObject("ImgEditDelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditPaste {
            get {
                object obj = ResourceManager.GetObject("ImgEditPaste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditRedo {
            get {
                object obj = ResourceManager.GetObject("ImgEditRedo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgEditUndo {
            get {
                object obj = ResourceManager.GetObject("ImgEditUndo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFileNew {
            get {
                object obj = ResourceManager.GetObject("ImgFileNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFileOpen {
            get {
                object obj = ResourceManager.GetObject("ImgFileOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFilePrint {
            get {
                object obj = ResourceManager.GetObject("ImgFilePrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFilePrintPreview {
            get {
                object obj = ResourceManager.GetObject("ImgFilePrintPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgFileSave {
            get {
                object obj = ResourceManager.GetObject("ImgFileSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgHelpAbout {
            get {
                object obj = ResourceManager.GetObject("ImgHelpAbout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveDown {
            get {
                object obj = ResourceManager.GetObject("ImgMoveDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveLeft {
            get {
                object obj = ResourceManager.GetObject("ImgMoveLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveRight {
            get {
                object obj = ResourceManager.GetObject("ImgMoveRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMoveUp {
            get {
                object obj = ResourceManager.GetObject("ImgMoveUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgMute {
            get {
                object obj = ResourceManager.GetObject("ImgMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNavigateBack {
            get {
                object obj = ResourceManager.GetObject("ImgNavigateBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgNavigateForward {
            get {
                object obj = ResourceManager.GetObject("ImgNavigateForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPause {
            get {
                object obj = ResourceManager.GetObject("ImgPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgPlay {
            get {
                object obj = ResourceManager.GetObject("ImgPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgRepeat {
            get {
                object obj = ResourceManager.GetObject("ImgRepeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgRun {
            get {
                object obj = ResourceManager.GetObject("ImgRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftDown {
            get {
                object obj = ResourceManager.GetObject("ImgShiftDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftLeft {
            get {
                object obj = ResourceManager.GetObject("ImgShiftLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftRight {
            get {
                object obj = ResourceManager.GetObject("ImgShiftRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShiftUp {
            get {
                object obj = ResourceManager.GetObject("ImgShiftUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShowBranching {
            get {
                object obj = ResourceManager.GetObject("ImgShowBranching", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgShowExitBranching {
            get {
                object obj = ResourceManager.GetObject("ImgShowExitBranching", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSkipBack {
            get {
                object obj = ResourceManager.GetObject("ImgSkipBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgSkipForward {
            get {
                object obj = ResourceManager.GetObject("ImgSkipForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgStop {
            get {
                object obj = ResourceManager.GetObject("ImgStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewLarge {
            get {
                object obj = ResourceManager.GetObject("ImgViewLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewMedium {
            get {
                object obj = ResourceManager.GetObject("ImgViewMedium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ImgViewSmall {
            get {
                object obj = ResourceManager.GetObject("ImgViewSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang4105\deflangfe4105{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}}
        ///{\colortbl ;\red53\green56\blue42;\red0\green0\blue255;\red255\green255\blue255;}
        ///{\stylesheet{ Normal;}{\s1 heading 1;}{\s2 heading 2;}{\s3 heading 3;}{\s4 heading 4;}}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\cbpat3\nowidctlpar\s3\sa200\sl240\slmult1\qc\cf1\b\f0\fs22 GNU GENERAL PUBLIC LICENSE\par
        ///\pard\cbpat3\nowidctlpar\sa200\sl240\slmult1\qc\b0\fs18 Version 3, 29 June 2007\par
        ///\pard [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseDetails {
            get {
                return ResourceManager.GetString("LicenseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang4105{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2509;}\viewkind4\uc1\pard\f0\fs18 Double Agent is free software, distributed in the hope that it will be useful, but with ABSOLUTELY NO WARRANTY.\par
        ///\par
        ///You can redistribute it and/or modify it under the terms of the \b GNU General Public License\b0  as published by the Free Software Foundation.  Click below to read a copy of the license.\par
        ///\par
        ///Double Agent is available for download at h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseIntro {
            get {
                return ResourceManager.GetString("LicenseIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth.
        /// </summary>
        internal static string MouthOverlay {
            get {
                return ResourceManager.GetString("MouthOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-closed.
        /// </summary>
        internal static string MouthOverlayClosed {
            get {
                return ResourceManager.GetString("MouthOverlayClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-medium.
        /// </summary>
        internal static string MouthOverlayMedium {
            get {
                return ResourceManager.GetString("MouthOverlayMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-narrow.
        /// </summary>
        internal static string MouthOverlayNarrow {
            get {
                return ResourceManager.GetString("MouthOverlayNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-1.
        /// </summary>
        internal static string MouthOverlayWide1 {
            get {
                return ResourceManager.GetString("MouthOverlayWide1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-2.
        /// </summary>
        internal static string MouthOverlayWide2 {
            get {
                return ResourceManager.GetString("MouthOverlayWide2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-3.
        /// </summary>
        internal static string MouthOverlayWide3 {
            get {
                return ResourceManager.GetString("MouthOverlayWide3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouth-wide-4.
        /// </summary>
        internal static string MouthOverlayWide4 {
            get {
                return ResourceManager.GetString("MouthOverlayWide4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation &quot;{0}&quot; already exists..
        /// </summary>
        internal static string MsgDuplicateAnimation {
            get {
                return ResourceManager.GetString("MsgDuplicateAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as {0} failed..
        /// </summary>
        internal static string MsgFailedSaveAs {
            get {
                return ResourceManager.GetString("MsgFailedSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid character file..
        /// </summary>
        internal static string MsgInvalidFile {
            get {
                return ResourceManager.GetString("MsgInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use &quot;Save As&quot; with the same file name..
        /// </summary>
        internal static string MsgInvalidSaveAs {
            get {
                return ResourceManager.GetString("MsgInvalidSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not contain a valid palette..
        /// </summary>
        internal static string MsgNoFilePalette {
            get {
                return ResourceManager.GetString("MsgNoFilePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to {0}?.
        /// </summary>
        internal static string MsgSaveFile {
            get {
                return ResourceManager.GetString("MsgSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to &quot;{0}&quot;?.
        /// </summary>
        internal static string MsgSaveNew {
            get {
                return ResourceManager.GetString("MsgSaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animation {0}.
        /// </summary>
        internal static string TitleAnimation {
            get {
                return ResourceManager.GetString("TitleAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Balloon.
        /// </summary>
        internal static string TitleBalloon {
            get {
                return ResourceManager.GetString("TitleBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name {1}.
        /// </summary>
        internal static string TitleCharacterName {
            get {
                return ResourceManager.GetString("TitleCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1} *].
        /// </summary>
        internal static string TitleDirtyFile {
            get {
                return ResourceManager.GetString("TitleDirtyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame {0}.
        /// </summary>
        internal static string TitleFrame {
            get {
                return ResourceManager.GetString("TitleFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - {0}.
        /// </summary>
        internal static string TitleFrameAnimation {
            get {
                return ResourceManager.GetString("TitleFrameAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image {0}.
        /// </summary>
        internal static string TitleImage {
            get {
                return ResourceManager.GetString("TitleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - {0}.
        /// </summary>
        internal static string TitleImageFrame {
            get {
                return ResourceManager.GetString("TitleImageFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new character.
        /// </summary>
        internal static string TitleNewFile {
            get {
                return ResourceManager.GetString("TitleNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [{1}].
        /// </summary>
        internal static string TitleOpenFile {
            get {
                return ResourceManager.GetString("TitleOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} overlay.
        /// </summary>
        internal static string TitleOverlay {
            get {
                return ResourceManager.GetString("TitleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} - {0}.
        /// </summary>
        internal static string TitleOverlayFrame {
            get {
                return ResourceManager.GetString("TitleOverlayFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state {0}.
        /// </summary>
        internal static string TitleState {
            get {
                return ResourceManager.GetString("TitleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text-to-Speech.
        /// </summary>
        internal static string TitleTts {
            get {
                return ResourceManager.GetString("TitleTts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string UndoActionAdd {
            get {
                return ResourceManager.GetString("UndoActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        internal static string UndoActionChange {
            get {
                return ResourceManager.GetString("UndoActionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut.
        /// </summary>
        internal static string UndoActionCut {
            get {
                return ResourceManager.GetString("UndoActionCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string UndoActionDelete {
            get {
                return ResourceManager.GetString("UndoActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste.
        /// </summary>
        internal static string UndoActionPaste {
            get {
                return ResourceManager.GetString("UndoActionPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change {0}.
        /// </summary>
        internal static string UndoAnimationName {
            get {
                return ResourceManager.GetString("UndoAnimationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1}.
        /// </summary>
        internal static string UndoAnimationNames {
            get {
                return ResourceManager.GetString("UndoAnimationNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string UndoAnimationSize {
            get {
                return ResourceManager.GetString("UndoAnimationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        internal static string UndoBalloonColor {
            get {
                return ResourceManager.GetString("UndoBalloonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font.
        /// </summary>
        internal static string UndoBalloonFont {
            get {
                return ResourceManager.GetString("UndoBalloonFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size.
        /// </summary>
        internal static string UndoBalloonSize {
            get {
                return ResourceManager.GetString("UndoBalloonSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to style.
        /// </summary>
        internal static string UndoBalloonStyle {
            get {
                return ResourceManager.GetString("UndoBalloonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string UndoDescription {
            get {
                return ResourceManager.GetString("UndoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to branching.
        /// </summary>
        internal static string UndoFrameBranching {
            get {
                return ResourceManager.GetString("UndoFrameBranching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        internal static string UndoFrameDuration {
            get {
                return ResourceManager.GetString("UndoFrameDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit branching.
        /// </summary>
        internal static string UndoFrameExit {
            get {
                return ResourceManager.GetString("UndoFrameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frame order.
        /// </summary>
        internal static string UndoFrameOrder {
            get {
                return ResourceManager.GetString("UndoFrameOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound.
        /// </summary>
        internal static string UndoFrameSoundPath {
            get {
                return ResourceManager.GetString("UndoFrameSoundPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unique identifier.
        /// </summary>
        internal static string UndoGuid {
            get {
                return ResourceManager.GetString("UndoGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon.
        /// </summary>
        internal static string UndoIcon {
            get {
                return ResourceManager.GetString("UndoIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        internal static string UndoImageFilePath {
            get {
                return ResourceManager.GetString("UndoImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string UndoImageOffset {
            get {
                return ResourceManager.GetString("UndoImageOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image order.
        /// </summary>
        internal static string UndoImageOrder {
            get {
                return ResourceManager.GetString("UndoImageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new frame duration.
        /// </summary>
        internal static string UndoNewFrameDuration {
            get {
                return ResourceManager.GetString("UndoNewFrameDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string UndoOverlayImagePath {
            get {
                return ResourceManager.GetString("UndoOverlayImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string UndoOverlayOffset {
            get {
                return ResourceManager.GetString("UndoOverlayOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace.
        /// </summary>
        internal static string UndoOverlayReplaceFlag {
            get {
                return ResourceManager.GetString("UndoOverlayReplaceFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palette.
        /// </summary>
        internal static string UndoPalette {
            get {
                return ResourceManager.GetString("UndoPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to palette transparency.
        /// </summary>
        internal static string UndoPaletteTransparency {
            get {
                return ResourceManager.GetString("UndoPaletteTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return animation.
        /// </summary>
        internal static string UndoReturnAnimation {
            get {
                return ResourceManager.GetString("UndoReturnAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uses {0}.
        /// </summary>
        internal static string UndoStateAnimation {
            get {
                return ResourceManager.GetString("UndoStateAnimation", resourceCulture);
            }
        }
    }
}
